api/urls.py
from django.conf.urls import include, url

# Rest framework
from rest_framework import routers
# Class based API views
from api.views import SectionCreationNewView, SectionDetailView
from api.views import CourseCreationNewView, CourseDetailView
from api.views import ParticipantCreationView, ParticipantDetailView
from api.views import UserView
from api.views import AuthView

router = routers.SimpleRouter()

app_name = 'api'
urlpatterns = [

    # Regular URLs

    # Class based URLs,
    url( r'^section/$', SectionCreationNewView.as_view(), name = 'section_list' ),
    url( r'^section/(?P<pk>[0-9]+)$', SectionDetailView.as_view(), name = 'section_detail' ),
    url( r'^course/$', CourseCreationNewView.as_view(), name = 'course_list' ),
    url( r'^course/(?P<pk>[0-9]+)$', CourseDetailView.as_view(), name = 'course_detail' ),
    url( r'^participant/$', ParticipantCreationView.as_view(), name = 'paticipant_list' ),
    url( r'^participant/(?P<pk>[0-9]+)$', ParticipantDetailView.as_view(), name = 'participant_detail' ),
    url(r'^accounts/$', UserView.as_view('list')),
    url(r'^auth/$', AuthView.as_view(), name='authenticate'),
    url( r'^', include(router.urls) ),
]

samacore/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'samacore'
partial_patterns = [
    url(
        r'^courseInfo/$',
        views.PartialGroupView.as_view(template_name='samacore/partials/courseInfo.html'),
        name='course_info',
        ),
    url(
        r'^courseInfoAdmin/$',
        views.PartialGroupView.as_view(template_name='samacore/partials/courseInfoAdmin.html'),
        name='course_info_admin',
        ),
    url(
        r'^courseRegistration/$',
        views.PartialGroupView.as_view(template_name='samacore/partials/courseRegistration.html'),
        name='course_registration',
        ),
    url(
        r'^courseEditParticipant/$',
        views.PartialGroupView.as_view(template_name='samacore/partials/courseEditParticipant.html'),
        name='course_participant_edition',
        ),
    url(r'^(?P<template_name>[a-zA-Z_]+\.html)$', views.PartialGroupView.as_view()),
]


urlpatterns = [
    # Examples:
    # url(r'^$', 'samaweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^partials/', include(partial_patterns, namespace='partials')),
    url(r'^partials/', include((partial_patterns, "samacore"), namespace='partials')),
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index, name='index'),
    url(r'^section/$', views.section, name='section'),
    url(r'^cours/$', views.courses, name='courses'),
    url(r'^specific_cours/$', views.course, name='course'),
    url(r'^register_cours/$', views.register_course, name='register_course'),
    url(r'^add_cours/$', views.add_course, name='add_course'),
    url(r'^edit_cours/$', views.edit_course, name='edit_course'),
    url(r'^archive_cours/$', views.archive_course, name='archive_course'),
    url(r'^participants_cours/$', views.participants_course, name='participants_course'),
    url(r'^participant_cours_edit/$', views.participant_course_edit, name='participant_course_edit'),
    url(r'^participant_cours_delete/$', views.participant_course_delete, name='participant_course_delete'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^membres/$', views.membres, name='membres'),
    url(r'^add_program/$', views.add_program, name='add_program'),
    url(r'^edit_program/$', views.edit_program, name='edit_program'),
    url(r'^admin_login/$', views.admin_login, name='admin_login'),
]

samaweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#from samacore import views

app_name = 'samaweb'
urlpatterns = [
    # Examples:
    # url(r'^$', 'samaweb.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^', include('samacore.urls', 'samacore')),
    #url(r'^', include('samacore.urls', namespace='samacore')),
    #url(r'^', include(('samacore.urls', 'samacore'), namespace='samacore')),
    #url(r'^section/$', samacore.views.section, name='section'),
    # Include API URLs0
    url(r'^api/', include('api.urls', 'api')),
]
urlpatterns += staticfiles_urlpatterns()

samacore/views.py
from django.shortcuts import render

from django.template import loader, RequestContext

from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, Http404
from django.core import exceptions
from django.conf import settings
from django.shortcuts import get_object_or_404

from django.views.generic import TemplateView
from samacore.models import Course, Participant
import simplejson as json
# Create your views here.

#from django.http import HttpResponse
courseprice = {
        'UPE': 90,
        'BLS-AED': 90,
        'Sauveteurs': 130,
        'IAS1': 150,
        'IAS2': 150,
        'Samaritains': 150
        }


def index(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    param_1 = 2
    context = {'params': param_1}
    return render(request, 'samacore/index.html', context)

def section(request):
    param_1 = 2
    context = {'params': param_1}
    return render(request, 'samacore/section.html', context)

def courses(request):
    param_1 = 2
    context = {'params': param_1}
    if request.user.is_anonymous:
        return render(request, 'samacore/courses.html', context)
    else:
        return render(request, 'samacore/courses_admin.html', context)

def faq(request):
    param_1 = 2
    context = {'params': param_1}
    return render(request, 'samacore/faq.html', context)

def membres(request):
    param_1 = 2
    context = {'params': param_1}
    if request.user.is_anonymous:
        return render(request, 'samacore/section_program_section.html', context)
    else:
        return render(request, 'samacore/section_program_section_admin.html', context)

def add_program(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        context = {}

        return render(request, 'samacore/section_program_add.html', context)

def edit_program(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        if 'sectionid' in request.GET:
            sectionid = request.GET['sectionid']

        context = {'sectionid': sectionid}

        return render(request, 'samacore/section_program_edit.html', context)


def course(request):
    coursetype = ''
    coursestatus = ''
    if 'coursetype' in request.GET:
        coursetype = request.GET['coursetype']

    if 'coursestatus' in request.GET:
        coursestatus = request.GET['coursestatus']

    context = {'coursetype': coursetype,
               'courseprice': courseprice[coursetype],
               'coursestatus': coursestatus}
    if request.user.is_anonymous:
        return render(request, 'samacore/course.html', context)
    else:
        return render(request, 'samacore/course_admin.html', context)

def add_course(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        coursetype = ''
        if 'coursetype' in request.GET:
            coursetype = request.GET['coursetype']

        context = {'coursetype': coursetype,
                   'courseprice': courseprice[coursetype]}

        return render(request, 'samacore/course_add.html', context)

def edit_course(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        coursetype = ''
        if 'coursetype' in request.GET:
            coursetype = request.GET['coursetype']

        if 'courseid' in request.GET:
            courseid = request.GET['courseid']

        context = {'coursetype': coursetype,
                   'courseprice': courseprice[coursetype],
                   'courseid': courseid}

        return render(request, 'samacore/course_edit.html', context)

def archive_course(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        coursetype = ''
        if 'coursetype' in request.GET:
            coursetype = request.GET['coursetype']

        if 'courseid' in request.GET:
            courseid = request.GET['courseid']

        context = {'coursetype': coursetype,
                   'courseprice': courseprice[coursetype],
                   'courseid': courseid}

        return render(request, 'samacore/course_archive.html', context)

def participants_course(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        coursetype = ''
        if 'coursetype' in request.GET:
            coursetype = request.GET['coursetype']

        if 'courseid' in request.GET:
            courseid = request.GET['courseid']

        context = {'coursetype': coursetype,
                   'courseid': courseid}

        return render(request, 'samacore/course_participants.html', context)

def participant_course_edit(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        coursetype = ''
        courseid = ''
        coursedates = ''
        coursetime = ''
        courselocation = ''
        participantid = ''
        if 'coursetype' in request.GET:
            coursetype = request.GET['coursetype']
        if 'courseid' in request.GEt:
            courseid = request.GET['courseid']
            course = Course.objects.get(id=courseid)
            courseinformation = course.additional_information
            jsoncourse = json.loads(courseinformation)
            coursedates     = jsoncourse['dates']
            coursetime      = jsoncourse['time']
            courselocation  = jsoncourse['location']
        if 'participantid' in request.GET:
            participantid = request.GET['participantid']
            participant = Participant.objects.get(id=participantid)

        context = {'coursetype': coursetype,
                   'courseprice': courseprice[coursetype],
                   'courseid': courseid,
                   'coursedates': coursedates,
                   'coursetime': coursetime,
                   'courselocation': courselocation,
                   'participantid': participantid,
                   'participant': participant}
        return render(request, 'samacore/participant_course.html', context)

def participant_course_delete(request):
    if request.user.is_anonymous:
        raise exceptions.PermissionDenied
    else:
        coursetype = ''
        courseid = ''
        coursedates = ''
        coursetime = ''
        courselocation = ''
        participantid = ''
        if 'coursetype' in request.GET:
            coursetype = request.GET['coursetype']
        if 'courseid' in request.GET:
            courseid = request.GET['courseid']
            course = Course.objects.get(id=courseid)
            courseinformation = course.additional_information
            jsoncourse = json.loads(courseinformation)
            coursedates     = jsoncourse['dates']
            coursetime      = jsoncourse['time']
            courselocation  = jsoncourse['location']
        if 'participantid' in request.GET:
            participantid = request.GET['participantid']
            participant = Participant.objects.get(id=participantid)

        context = {'coursetype': coursetype,
                   'courseprice': courseprice[coursetype],
                   'courseid': courseid,
                   'coursedates': coursedates,
                   'coursetime': coursetime,
                   'courselocation': courselocation,
                   'participantid': participantid,
                   'participant': participant}
        return render(request, 'samacore/course_participant_delete.html', context)


def admin_login(request):
    param_1 = 2
    context = {'params': param_1}
    return render(request, 'samacore/admin_login.html', context)

def register_course(request):
    coursetype = ''
    courseid = ''
    coursedates = ''
    coursetime = ''
    courselocation = ''
    if 'coursetype' in request.GET:
        coursetype = request.GET['coursetype']
    if 'courseid' in request.GET:
        courseid = request.GET['courseid']
        course = Course.objects.get(id=courseid)
        courseinformation = course.additional_information
        jsoncourse = json.loads(courseinformation)
        coursedates     = jsoncourse['dates']
        coursetime      = jsoncourse['time']
        courselocation  = jsoncourse['location']


    context = {'coursetype': coursetype,
               'courseprice': courseprice[coursetype],
               'courseid': courseid,
               'coursedates': coursedates,
               'coursetime': coursetime,
               'courselocation': courselocation}
    return render(request, 'samacore/register_course.html', context)

#------------------------------------------------


class PartialGroupView(TemplateView):
    def get_template_names(self):
        if 'template_name' in self.kwargs:
            self.template_name = 'samacore/partials/' + self.kwargs.get('template_name')
        return super(PartialGroupView, self).get_template_names()

    def get_context_data(self, **kwargs):
        context = super(PartialGroupView, self).get_context_data(**kwargs)
        return context


#------------------------------------------------

templates/samacore/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en" data-ng-app="samawebApp">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Section des Samaritains - Martigny</title>

    <!-- Favicon for the website -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}"/>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-+Ga2s7YBbhOD6nie0DzrZpJes+b2K1xkpKxTFFcx59QmVPaSA8c7pycsNaFwUK6l" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-7ox8Q2yzO/uWircfojVuCQOZl+ZZBg2D2J5nkpLqzH1HY0C1dHlTKIbpRz/LG23c" crossorigin="anonymous"></script>


    <!-- Custom Styles -->
    <link href="{% static 'css/course_style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/section_style.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/registration_style.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <div Class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- <a class="navbar-brand" href="index.html">Samaritains de Martigny</a>-->
               <a class="navbar-brand" href="{% url 'samacore:index' %}">Samaritains de Martigny</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'samacore:section' %}">Section</a>
                    </li>
                    <li>
                        <a href="{% url 'samacore:courses' %}">Cours</a>
                    </li>
                    <li>
                        <a href="{% url 'samacore:faq' %}">FAQ</a>
                    </li>
                    <li>
                        <a href="{% url 'samacore:membres' %}">Membres</a>
                    </li>
                    <li>
                        <a href="{% url 'samacore:admin_login' %}">Admin</a>
                    </li>

                    <!--
                    <li>
                        <a href="services.html">Services</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="portfolio-1-col.html">1 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-2-col.html">2 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-3-col.html">3 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-4-col.html">4 Column Portfolio</a>
                            </li>
                            <li>
                                <a href="portfolio-item.html">Single Portfolio Item</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="blog-home-1.html">Blog Home 1</a>
                            </li>
                            <li>
                                <a href="blog-home-2.html">Blog Home 2</a>
                            </li>
                            <li>
                                <a href="blog-post.html">Blog Post</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="full-width.html">Full Width Page</a>
                            </li>
                            <li>
                                <a href="sidebar.html">Sidebar Page</a>
                            </li>
                            <li>
                                <a href="faq.html">FAQ</a>
                            </li>
                            <li>
                                <a href="404.html">404</a>
                            </li>
                            <li>
                                <a href="pricing.html">Pricing Table</a>
                            </li>
                        </ul>
                    </li> -->
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </div>
    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- jQuery Validate -->

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Bootbox to handle modals and dialog boxes -->
    <script src="{% static 'js/bootbox.min.js' %}"></script>

    <!-- AngularJS -->
    <script src="{% static 'js/angular.min.js' %}"></script>
    <script src="{% static 'js/angular-ui-router.min.js' %}"></script>

    <!-- Custom libs -->
    <script src="{% static 'js/base_64_encoder_decoder.js' %}"></script>

    <!-- Required libs for pdfmake -->
    <script src="{% static 'js/pdfmake.min.js' %}"></script>
    <script src="{% static 'js/vfs_fonts.js' %}"></script>

    <!-- App libs -->
    <script src="{% static 'samaweb/app/app.js' %}"></script>
    <script src="{% static 'samaweb/app/app.config.js' %}"></script>
    <script src="{% static 'samaweb/app/controllers/sectionController.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'samaweb/app/controllers/courseController.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'samaweb/app/controllers/authController.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'samaweb/app/services/authStateService.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'samaweb/app/factories/sectionFactory.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'samaweb/app/factories/courseFactory.js' %}" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'samaweb/app/factories/authFactory.js' %}" type="text/javascript" charset="utf-8"></script>

    <div id="outerdiv" ng-controller="courseController" ng-init="authState.user='{{user.username}}'">
    {% block content %}{% endblock %}
    </div>
</body>

</html>

templates/samacore/course.html
{% extends "samacore/base.html" %}

{% load static %}

{% block title %}FAQ{% endblock %}

{% block section %}faq{% endblock %}

{% block content %}

    <!-- Page Content -->
    <div class="container" ng-init="initCourse('{{ coursetype }}', '{{ courseprice }}', '{% url 'api:course_list' %}')">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <button type="button" class="btn btn-warning button_new_course" ng-if="authState.user">
                  <i class="fa fa-plus-circle fa-2x"></i> Ajouter un nouveau cours
                </button>
                <h1 class="page-header">{{ coursetype }}
                <img ng-if="course_type == 'Sauveteurs'" class="img-responsive course-img" src="{% static 'img/car-icon.png' %}" alt="">
                <img ng-if="course_type == 'Samaritains'" class="img-responsive course-img" src="{% static 'img/medicine-box-icon.png' %}" alt="">
                <img ng-if="course_type == 'BLS-AED'" class="img-responsive course-img" src="{% static 'img/heart-beat-icon.png' %}" alt="">
                <img ng-if="course_type == 'UPE'" class="img-responsive course-img" src="{% static 'img/medical-cap-icon.png' %}" alt="">

                <small>Diverses dates de cours proposées</small>
                </h1>
                <ol class="breadcrumb">
                <h2>Inscription à un cours</h2>
                <p>Parmi l'offre de cours <b>{{ coursetype }}</b> de l'année, choisissez le cours avec les dates qui vous conviennent, ci-dessous, et cliquez sur <b>Inscription</b></p>
                <p>Vous serez guidés pas à pas durant le processus d'inscription. Nous vous prions déjà de bien vouloir rentrer <b>toutes vos coordonnées correctement</b></p>
               </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Courses -->
       <div ui-view="courseInfo"></div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; SamaMartigny 2018</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
    <script type='text/javascript'>
        $(document).ready(function() {
            $('.collapse').on('show.bs.collapse', function() {
                var id = $(this).attr('id');
                $('a[href="#' + id + '"]').closest('.panel-heading').addClass('active-faq');
                $('a[href="#' + id + '"] .panel-title span').html('<i class="glyphicon glyphicon-minus"></i>');
            });
            $('.collapse').on('hide.bs.collapse', function() {
                var id = $(this).attr('id');
                $('a[href="#' + id + '"]').closest('.panel-heading').removeClass('active-faq');
                $('a[href="#' + id + '"] .panel-title span').html('<i class="glyphicon glyphicon-plus"></i>');
            });
        });
    </script>
    <script type='text/javascript'>
    jQuery(document).ready(function() {
        //var url = "{% url 'api:course_list' %}";
        //$.ajax({
        //    type: "GET",
        //    url: url,
        //    data: {
        //        coursetype: "{{ coursetype }}",
        //    },
        //    contentType: "application/json; charset=utf-8",
        //    dataType: "json",

        //    success: function(data) {
        //        console.log(data);
        //    },

        //    error: function(jqXHR, textStatus, errorThrown) {
        //        alert('Error: ' + errorThrown);
        //    }
        //});

    });
    </script>
{% endblock %}

templates/samacore/course_admin.html
{% extends "samacore/base.html" %}

{% load static %}

{% block title %}FAQ{% endblock %}

{% block section %}faq{% endblock %}

{% block content %}

    <!-- Page Content -->
    <div class="container" ng-init="initCourse('{{ coursetype }}', '{{ courseprice }}', '{% url 'api:course_list' %}')">

        <!-- Page Heading/Breadcrumbs -->
        <div class="row" ng-show="authState.user">
            <div class="col-lg-12">
            <div class="alert alert-danger alert_login" role="alert">
                <b>Avec de grands pouvoirs, viennent de grande responsabilité!</b> N'oubliez pas que <i>vous êtes connecté</i> en tant que <b>{$ authState.user $}</b></br>
            Cela signifie que vous souhaitez faire des modifications au contenu du site. Si ce n'est pas le cas, vous êtes priés de vous <i>déconnecter </i> depuis le menu <b>Admin</b>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <a id="btn_course_add" href="{{URL_PREFIX}}/add_cours/?coursetype={{ coursetype }}" class="btn btn-warning button_actions_course" ng-if="authState.user">
                    <i class="fa fa-plus-circle fa-2x"></i> Ajouter un nouveau cours
                </a>
                <h1 class="page-header">{{ coursetype }}
                <img ng-if="course_type == 'Sauveteurs'" class="img-responsive course-img" src="{% static 'img/car-icon.png' %}" alt="">
                <img ng-if="course_type == 'Samaritains'" class="img-responsive course-img" src="{% static 'img/medicine-box-icon.png' %}" alt="">
                <img ng-if="course_type == 'BLS-AED'" class="img-responsive course-img" src="{% static 'img/heart-beat-icon.png' %}" alt="">
                <img ng-if="course_type == 'UPE'" class="img-responsive course-img" src="{% static 'img/medical-cap-icon.png' %}" alt="">

                <small>Diverses dates de cours proposées</small>
                </h1>
                <ol class="breadcrumb">
                <h2>Inscription à un cours</h2>
                <p>Parmi l'offre de cours <b>{{ coursetype }}</b> de l'année, choisissez le cours avec les dates qui vous conviennent, ci-dessous, et cliquez sur <b>Inscription</b></p>
                <p>Vous serez guidés pas à pas durant le processus d'inscription. Nous vous prions déjà de bien vouloir rentrer <b>toutes vos coordonnées correctement</b></p>
               </ol>
            </div>
        </div>
        <!-- /.row -->

        <!-- Courses -->
       <div ng-show="authState.user" ui-view="courseInfoAdmin"></div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; SamaMartigny 2018</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->
    <script type='text/javascript'>
        $(document).ready(function() {
            $('.collapse').on('show.bs.collapse', function() {
                var id = $(this).attr('id');
                $('a[href="#' + id + '"]').closest('.panel-heading').addClass('active-faq');
                $('a[href="#' + id + '"] .panel-title span').html('<i class="glyphicon glyphicon-minus"></i>');
            });
            $('.collapse').on('hide.bs.collapse', function() {
                var id = $(this).attr('id');
                $('a[href="#' + id + '"]').closest('.panel-heading').removeClass('active-faq');
                $('a[href="#' + id + '"] .panel-title span').html('<i class="glyphicon glyphicon-plus"></i>');
            });
        });
    </script>
    <script type='text/javascript'>
    jQuery(document).ready(function() {
        //var url = "{% url 'api:course_list' %}";
        //$.ajax({
        //    type: "GET",
        //    url: url,
        //    data: {
        //        coursetype: "{{ coursetype }}",
        //    },
        //    contentType: "application/json; charset=utf-8",
        //    dataType: "json",

        //    success: function(data) {
        //        console.log(data);
        //    },

        //    error: function(jqXHR, textStatus, errorThrown) {
        //        alert('Error: ' + errorThrown);
        //    }
        //});

    });
    </script>
{% endblock %}